### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by Jordaar** [VeraxonHD/aegis-bot#12]
await element.fetch()
                ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by VeraxonHD** [comment]
Hi.

I'm no longer giving support to people looking to self-host
If you'd like to invite Aegis please use [this link](https://discord.com/oauth2/authorize?client_id=416349322620305408&scope=bot&permissions=1564994678)

Thanks
